In [51]:
import tensorflow as tf

## 10. a)

In [64]:
A = tf.random.uniform(shape=[3,5], minval=-10, maxval=10, dtype='int64')
A

<tf.Tensor: shape=(3, 5), dtype=int64, numpy=
array([[  9, -10,  -2,   8,  -6],
       [ -8,  -2,   5,   6,   6],
       [  0,   5,   7,  -9, -10]], dtype=int64)>

In [65]:
B = tf.random.uniform(shape=[5,4], minval=-10, maxval=10, dtype='int64')
B

<tf.Tensor: shape=(5, 4), dtype=int64, numpy=
array([[-5,  0,  5, -6],
       [ 7,  5, -3,  6],
       [ 7,  2,  1,  1],
       [ 8, -1, -2, -6],
       [ 5,  5,  3, -8]], dtype=int64)>

In [66]:
import numpy as np
np.savetxt('Matrizen_Ordner\\MatrixA.csv', A, delimiter=',')

In [67]:
np.savetxt('Matrizen_Ordner\\MatrixB.csv', B, delimiter=',')

## 10. b)

In [68]:
import pandas as pd

dfA = pd.read_csv('Matrizen_Ordner\\MatrixA.csv', header=None)
dfA

0     1    2    3     4
0  9.0 -10.0 -2.0  8.0  -6.0
1 -8.0  -2.0  5.0  6.0   6.0
2  0.0   5.0  7.0 -9.0 -10.0

In [69]:
dfB = pd.read_csv('Matrizen_Ordner\\MatrixB.csv', header=None)
dfB

0    1    2    3
0 -5.0  0.0  5.0 -6.0
1  7.0  5.0 -3.0  6.0
2  7.0  2.0  1.0  1.0
3  8.0 -1.0 -2.0 -6.0
4  5.0  5.0  3.0 -8.0

## 10. c)

In [70]:
print("MatrixA:", A)
print("MatrixB:", B)
print("Ergebnis:", tf.matmul(A,B))

MatrixA: tf.Tensor(
[[  9 -10  -2   8  -6]
 [ -8  -2   5   6   6]
 [  0   5   7  -9 -10]], shape=(3, 5), dtype=int64)
MatrixB: tf.Tensor(
[[-5  0  5 -6]
 [ 7  5 -3  6]
 [ 7  2  1  1]
 [ 8 -1 -2 -6]
 [ 5  5  3 -8]], shape=(5, 4), dtype=int64)
Ergebnis: tf.Tensor(
[[ -95  -92   39 -116]
 [ 139   24  -23  -43]
 [ -38   -2  -20  171]], shape=(3, 4), dtype=int64)
